package com.facilon.app.module.client.dto.onboarding;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

/**
 * Payload for {@code POST /api/clients/pms-investor/register}.
 *
 * Superset of the Laravel form fields posted to
 * {@code InvestorController.introduce_investor_pms_register_step4_insert_data}
 * (see {@code introduce-pms-register-step4.blade.php}) — all of the Laravel
 * parity fields (nationality, pancard, oci, Indian origin, WhatsApp,
 * confirmation, privacy) are optional here because the same endpoint is also
 * used by the "Self registration" path where some of them do not apply.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PmsInvestorRegistrationDto {

    // --- Identity (required) ---
    @NotBlank
    private String firstName;

    private String middleName;

    @NotBlank
    private String lastName;

    @NotBlank
    @Email
    private String email;

    @NotBlank
    private String mobilePhone;

    @NotBlank
    private String password;

    // --- Demographics (Laravel parity) ---
    /** ISO yyyy-MM-dd. Laravel source field: user_dob. */
    private LocalDate userDob;
    /** "Male" | "Female" | "Transgender". */
    private String gender;
    /** ISD / country-code master id. Laravel source field: country_code. */
    private Long countryCodeId;
    /** Laravel source field: nationality (master_nationality.ss_nationalityid). */
    private Long nationalityId;
    /** Human-readable nationality name (cached from the master lookup). */
    private String nationalityName;
    /** Laravel source field: legal_country / legal_country2 (master_countries.ss_countryid). */
    private Long legalCountryId;
    /** "Self" | "Legal Entity". Laravel source field: Self (hidden input). */
    private String registerAs;
    /** Legal entity full name (only used when registerAs == "Legal Entity"). */
    private String legalEntityFullName;
    /** Full display name — Laravel source field: full_name. */
    private String fullName;

    // --- Conditional KYC ---
    /** "Yes" | "No". Laravel source field: pancard. */
    private String pancard;
    /** "Yes" | "No". Laravel source field: oci_card. */
    private String ociCard;
    /** "Yes" | "No". Laravel source field: indian_origin. */
    private String indianOrigin;

    // --- WhatsApp / consent ---
    /** "Yes" | "No" — Laravel source field: same_whatsapp. */
    private String sameWhatsapp;
    /** Alternate WhatsApp number when sameWhatsapp == "No". */
    private String diffMobWhatsapp;
    /** Boolean flag — Laravel source field: agree_to_watsapp. */
    private Boolean agreeToWhatsapp;
    /** Boolean flag — Laravel source field: agree_for_otp. */
    private Boolean agreeForOtp;
    /** Marketing / confirmation opt-in — Laravel source field: confirmation. */
    private Boolean confirmation;
    /** Required — Laravel source field: agree_privacy. */
    private Boolean agreePrivacy;
    /** Required — Laravel source field: agree_terms. */
    private Boolean agreeTerms;

    // --- PMS-specific ---
    //
    // ALL THREE references are now optional. The Laravel PMS flow does NOT
    // collect manager / plan / bank from the user — they are inherited from
    // the introducer's Dataverse record (see InnerPageController
    // .introduce_investor_register_pms_main_step_show). Until the Spring side
    // implements the same Dataverse pre-fetch, the React wizard can't supply
    // them either, so we accept null values and skip the {@code InvestorPmsDetails}
    // row when no link is provided.
    private Long pmsManagerId;

    private Long pmsPlanId;

    private Long pmsBankId;

    /** Auto-generated by the React wizard (e.g. {@code "PENDING-1712345678"}). */
    private String accountNumber;

    /** Defaults to today on the React side when no link is provided. */
    private LocalDate agreementDate;

    private String comments;
}
