-- Migration for Introduced Registration Sessions table
CREATE TABLE IF NOT EXISTS introduced_registration_sessions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    unique_code VARCHAR(50) NOT NULL UNIQUE,
    dataverse_investor_id VARCHAR(100) NOT NULL COMMENT 'Display name like INV-1744',
    dataverse_investor_guid VARCHAR(100) NOT NULL COMMENT 'Actual Dataverse GUID',
    email VARCHAR(255) NOT NULL,
    mobile_number VARCHAR(20),
    country_code VARCHAR(10),
    first_name VARCHAR(100),
    middle_name VARCHAR(100),
    last_name VARCHAR(100),
    gender VARCHAR(20),
    date_of_birth DATE,
    current_step INT NOT NULL DEFAULT 0 COMMENT '0=consent, 1=otp_sent, 2=otp_verified, 3=details, 5=completed',
    consent_given BOOLEAN NOT NULL DEFAULT FALSE,
    consent_given_at TIMESTAMP NULL,
    email_otp_verified BOOLEAN NOT NULL DEFAULT FALSE,
    mobile_otp_verified BOOLEAN NOT NULL DEFAULT FALSE,
    registration_completed BOOLEAN NOT NULL DEFAULT FALSE,
    completed_at TIMESTAMP NULL,
    expires_at TIMESTAMP NOT NULL,
    tenant_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    modified_by VARCHAR(255),
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE,
    INDEX idx_unique_code (unique_code),
    INDEX idx_dataverse_investor_id (dataverse_investor_id),
    INDEX idx_email (email),
    INDEX idx_registration_completed (registration_completed)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Tracks introduced investor registration sessions';
